/**
 * Onboarding manual test cases — source: `OnboardingApp_Test_Plan.xlsx` (58 scenarios, sheets
 * "Test Cases" + "Legend"), supplied by the user 2026-09-24 for the playwright-automation-c1 →
 * C1 framework migration (Onboarding batch; plan §3.2 ONB rows, B1/B5).
 *
 * Emitted by _generate.js into BOTH Onboarding_test_cases.md and .xlsx — never hand-edit those two;
 * change this file and regenerate (SKILL golden rules 6 and 11).
 *
 * AUTOMATION SCOPE (user, 2026-09-24): rows coloured RED or YELLOW in the source workbook are NOT
 * for automation. They stay in this register as manual cases (`scope: RED` / `scope: YELLOW`).
 *   RED    (10) — TC_LOGIN_012/013/014, TC_XCUT_001…007: Okta SSO, CambridgeGO/Edulog provisioning,
 *                 social sign-in (third-party identity providers).
 *   YELLOW (3)  — TC_LOGIN_008/009/010: bulk-created username accounts; the first-login Terms gate
 *                 shows only once per account.
 *
 * ID RULES (AGENTS.md Rule 6, ADR-011, SKILL golden rules 3/7/10):
 *  - <MOD> = the page object the case will live on. Numbering continues each module's registry +
 *    test-file + register maximum (checked 2026-09-24): LAND 6+, FOOT 12+, LOGI 7+, RESE 6+,
 *    SNUP 65+, CREA 31+, SPRF 24+, PCHD 1+ (`parentChild.page.js` / `parentChild.test.js` — approved).
 *  - Where an EXISTING TC already asserts a row's outcome, the row REUSES that ID (`existing: true`)
 *    instead of minting a duplicate function (ADR-011). Its Remarks say what Phase 1 must confirm.
 *  - Source TC_HOME_005 / TC_HOME_006 (several footer links in one row) are split one row per link,
 *    because each link already has its own FOOT TC.
 *
 * GROUNDING: expected results are the source team's (its Legend states the age-gate thresholds were
 * "confirmed live"); they were NOT re-executed by us in this session. The source's own unverified
 * points are marked [ASSUMED]. Confirm live in c1-test-authoring Phase 1.
 */

const RED = 'RED';
const YELLOW = 'YELLOW';

// Sub-module groups, in source order (the .md prints one heading per group).
const GROUPS = [
  'Homepage',
  'Login',
  'Forgot Password',
  'Learner Password Reset (by Staff)',
  'Sign Up - Role Selection',
  'Sign Up - Learner',
  'Sign Up - Teacher',
  'Sign Up - Parent',
  'Parent / Child Account',
  'Class Invite',
  'Cross-Cutting',
];

// One requirement per SOURCE row: "<source id> — <source title>". Order = source order.
const REQS = [
  ['Homepage', 'TC_HOME_001 — Verify the pre-login homepage displays the expected header, hero, and footer elements'],
  ['Homepage', "TC_HOME_002 — Verify 'Log in' on the homepage navigates to the Log in page"],
  ['Homepage', "TC_HOME_003 — Verify 'Sign up' on the homepage navigates to the role-selection page"],
  ['Homepage', 'TC_HOME_004 — Verify the site-language switcher changes the language of the pre-login homepage'],
  ['Homepage', 'TC_HOME_005 — Verify the internal footer links (Terms of use, Privacy notice, Accessibility, Cambridge One for schools) each open their correct page in the same tab'],
  ['Homepage', 'TC_HOME_006 — Verify the external footer links (Our approach, FAQs, Help) each open their correct page in a new tab'],
  ['Homepage', 'TC_HOME_007 — Verify primary login page - {url}/login-primary'],
  ['Homepage', 'TC_HOME_008 — Verify secondary login page - {url}/login-secondary'],
  ['Login', 'TC_LOGIN_001 — Verify a user can log in successfully with valid credentials'],
  ['Login', 'TC_LOGIN_002 — Verify blank submission of the login form shows required-field validation'],
  ['Login', 'TC_LOGIN_003 — Verify login fails with an incorrect password and shows the generic credentials error'],
  ['Login', 'TC_LOGIN_004 — Verify the account is temporarily locked after 5 consecutive failed login attempts'],
  ['Login', "TC_LOGIN_005 — Verify the 'Show Password' toggle reveals and re-hides the password on the login form"],
  ['Login', "TC_LOGIN_006 — Verify 'Forgotten your password?' navigates to the Reset password screen"],
  ['Login', "TC_LOGIN_007 — Verify 'Don't have an account yet?' on the login form navigates to Sign up"],
  ['Login', 'TC_LOGIN_008 — Verify a learner with a username-based account (no email) can log in using their username'],
  ['Login', 'TC_LOGIN_009 — Verify a bulk-created adult username account logging in for the second time does not have to accept the Terms of use'],
  ['Login', 'TC_LOGIN_010 — Verify the first-login Terms of use onboarding gate does not let the user proceed without accepting'],
  ['Login', 'TC_LOGIN_011 — Verify an Admin can log in via the standard Log in form'],
  ['Login', 'TC_LOGIN_012 — Verify a Support Admin logs in via Okta single sign-on'],
  ['Login', 'TC_LOGIN_013 — Verify a CambridgeGO-provisioned user can log in'],
  ['Login', 'TC_LOGIN_014 — Verify an Edulog-provisioned user can log in'],
  ['Login', 'TC_LOGIN_015 — Verify logging out as a Learner lands on the pre-login home page'],
  ['Forgot Password', 'TC_FPWD_001 — Verify submitting the Reset password form with a blank email shows a required-field error'],
  ['Forgot Password', 'TC_FPWD_002 — Verify submitting the Reset password form with a valid email shows a generic confirmation, without revealing whether the account exists'],
  ['Forgot Password', 'TC_FPWD_003 — Verify submitting the Reset password form with an email that has no matching account shows the same generic confirmation message'],
  ['Forgot Password', "TC_FPWD_004 — Verify 'Back to login' returns from the Reset password screen to the Log in form"],
  ['Forgot Password', 'TC_FPWD_005 — Verify a user can set a new password via the emailed reset link and log in with the updated password'],
  ['Forgot Password', 'TC_FPWD_006 — Verify a user can log in with the newly reset password after resetting it via the emailed link'],
  ['Learner Password Reset (by Staff)', 'TC_RESETPW_001 — Verify a Teacher can set a temporary password for an enrolled student, and the student sets their own new password on first login with it'],
  ['Learner Password Reset (by Staff)', 'TC_RESETPW_002 — Verify an Admin can set a temporary password for a student from the Students tab, and the student sets their own new password on first login with it'],
  ['Sign Up - Role Selection', 'TC_ROLE_001 — Verify the role-selection page shows Learner, Teacher, and Parent options with no role pre-selected'],
  ['Sign Up - Role Selection', "TC_ROLE_002 — Verify selecting a role and clicking 'Next' shows a confirmation dialog naming the selected role"],
  ['Sign Up - Role Selection', "TC_ROLE_003 — Verify 'No, go back' on the role-confirmation dialog closes the dialog and keeps the previously selected role"],
  ['Sign Up - Role Selection', "TC_ROLE_004 — Verify 'Yes, continue' on the role-confirmation dialog proceeds to that role's registration flow"],
  ['Sign Up - Role Selection', "TC_ROLE_005 — Verify 'Login' on the role-selection page navigates to the Log in form"],
  ['Sign Up - Learner', 'TC_LRN_001 — Verify selecting the Learner role leads to an age and location screen before the registration form'],
  ['Sign Up - Learner', 'TC_LRN_002 — Verify selecting an under-age value on the Learner age screen blocks self-registration'],
  ['Sign Up - Learner', 'TC_LRN_003 — Verify the Learner under-age threshold depends on the selected Location'],
  ['Sign Up - Learner', 'TC_LRN_004 — Verify selecting an age of 16 or older on the Learner age screen allows the user to proceed to the registration form'],
  ['Sign Up - Learner', 'TC_LRN_005 — Verify a Learner (16+, India) can complete the registration form and create an account'],
  ['Sign Up - Learner', 'TC_LRN_006 — Verify the Learner registration form shows validation errors for blank required fields, an invalid email, and a weak password'],
  ['Sign Up - Teacher', 'TC_TCH_001 — Verify a Teacher can complete the registration form and create an account'],
  ['Sign Up - Teacher', 'TC_TCH_002 — Verify the Teacher registration form shows validation errors for blank required fields, an invalid email, a weak password, and an unchecked Terms checkbox'],
  ['Sign Up - Parent', 'TC_PAR_001 — Verify a Parent can complete the registration form and create an account'],
  ['Sign Up - Parent', "TC_PAR_002 — Verify the Parent registration form requires the 'parent or guardian' age-confirmation checkbox before submitting"],
  ['Parent / Child Account', "TC_CHLD_001 — Verify a Parent can create a child's account from 'My children'"],
  ['Parent / Child Account', "TC_CHLD_002 — Verify 'Next' on 'Create my child's account' stays blocked until every required field and the consent checkbox are complete"],
  ['Parent / Child Account', "TC_CHLD_003 — Verify a newly created child's account can log in for the first time"],
  ['Class Invite', 'TC_INVITE_001 — Verify a brand-new user invited to a class by a teacher can sign up via the invite email'],
  ['Class Invite', 'TC_INVITE_002 — Verify an existing, already-registered learner who clicks a class invite link while logged in is taken to their own dashboard'],
  ['Cross-Cutting', 'TC_XCUT_001 — Verify social sign-in buttons (Facebook, Google, Apple) are present on the Log in form'],
  ['Cross-Cutting', 'TC_XCUT_002 — Verify social sign-in buttons (Facebook, Google, Apple) are present on the Teacher registration form'],
  ['Cross-Cutting', 'TC_XCUT_003 — Verify social sign-in buttons (Facebook, Google, Apple) are present on the Learner registration form'],
  ['Cross-Cutting', 'TC_XCUT_004 — Verify social sign-in buttons (Facebook, Google, Apple) are present on the Parent registration form'],
  ['Cross-Cutting', "TC_XCUT_005 — Verify 'Sign in with Facebook' opens Facebook's own login page to authenticate"],
  ['Cross-Cutting', "TC_XCUT_006 — Verify 'Sign in with Google' opens Google's own sign-in page to authenticate"],
  ['Cross-Cutting', "TC_XCUT_007 — Verify 'Sign in with Apple' opens Apple's own sign-in page to authenticate"],
  ['Cross-Cutting', "TC_XCUT_008 — Verify 'Have an account already? / Login' on a registration form returns to the Log in page"],
  ['Cross-Cutting', 'TC_XCUT_009 — UI/Colors – Verify there are no unexpected color or UI changes on onboarding pages'],
];
const R = Object.fromEntries(REQS.map(([, r]) => [r.split(' — ')[0], r]));
const GROUP_OF = Object.fromEntries(REQS.map(([g, r]) => [r, g]));

// Source rows with no case of their own — the coverage map prints the reason.
const NOT_COVERED = {
  [R.TC_XCUT_009]: 'none — not a functional case. A look-and-feel regression check is what the framework\'s VISUAL layer does ' +
    '(AGENTS.md §8: `visualTest` baselines per TC, Phase 3). Covered by promoting the onboarding TCs above to ' +
    '`visualTest: true` once they are green — decided per TC at Phase 3, not designed as a manual case here.',
};

// ── shared text ────────────────────────────────────────────────────────────────────────────
const LOGGED_OUT = 'User is not logged in; pre-login homepage open.';
const ON_LOGIN = 'User is on the Log in page (homepage → "Log in").';
const ON_RESET = 'User is on the "Reset password" screen (Log in → "Forgotten your password?").';
const ON_ROLES = 'User is on the role-selection page (homepage → "Sign up", URL /regoptions).';
const TO_LEARNER_FORM = 'Learner registration form reached: role "Learner" → "Yes, continue" → age 16+ with location "India" → "Next".';
const SRC = 'Source: OnboardingApp_Test_Plan.xlsx. ';
const PW = 'Passwords come from `{{env.*}}` tokens, never plaintext test data (ADR-023).';
const EXISTING = (id, what) => 'EXISTING TC reused (ADR-011 — no duplicate function): ' + id + ' already ' + what + ' Phase 1: confirm it asserts this row\'s Expected Result; extend its assertion if it does not.';
const CREATES = 'CREATES REAL DATA (a platform account) — ADR-021: needs the user\'s OK on a shared environment; place in a data-creating suite. ';
const THOR_VERIFY = 'Thor: the e-mail verification link host has an EXPIRED certificate (c1-core-shared.md §A4) — the verify step is blocked on thor until renewed; production works. ';
const NOT_AUTO_RED = 'NOT FOR AUTOMATION — marked RED in the source plan (user, 2026-09-24): third-party identity provider. Manual execution only. ';
const NOT_AUTO_YELLOW = 'NOT FOR AUTOMATION — marked YELLOW in the source plan (user, 2026-09-24): needs bulk-created username accounts; the first-login gate appears once per account. Manual execution only. ';

const SOCIAL = "'Sign in with Facebook', 'Sign in with Google' and 'Sign in with Apple' buttons are shown";

const T = (req, o) => Object.assign({ req, type: 'Positive', priority: 'Medium', data: '—', scope: 'AUTO' }, o);

const TCS = [
  // ── Homepage ───────────────────────────────────────────────────────────────────────────
  T(R.TC_HOME_001, { id: 'TST_LAND_TC_6', priority: 'Medium',
    status: 'Pass', actual: 'Verified on Production: header logo/home link, language switcher, login/signup buttons, heading text, and all footer links are visible.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: 'Verify the pre-login homepage shows the expected header, hero and footer elements when it loads',
    pre: LOGGED_OUT, steps: '1. Go to the pre-login homepage.',
    expected: "1. Header: Cambridge One logo/home link, 'Help' link, the site-language switcher and a 'Log in' link.\n" +
      "2. Hero: heading 'Cambridge One', sub-heading 'Your home for digital learning', a 'Log in' link and a 'Sign up' link.\n" +
      "3. Footer: 'Terms of use', 'Privacy notice', 'Accessibility', 'Our approach', 'FAQs', 'Cambridge One for schools', a copyright line and 'Help'.",
    remarks: SRC + 'Extends the existing TST_LAND_TC_5 (hero heading/sub-heading/buttons/logo) with the header and footer items — a new function, not a duplicate.' }),
  T(R.TC_HOME_002, { id: 'TST_LAND_TC_3', priority: 'High', existing: true,
    status: 'Pass', actual: 'Verified on Production: clicking Log in navigates to the login page (/login).', comments: 'Automated in onboardingB1Test_prod (Suite 2, Suite 3)',
    title: "Verify the Log in page opens when 'Log in' is clicked on the homepage",
    pre: LOGGED_OUT, steps: "1. Click 'Log in'.",
    expected: "The Log in page opens (URL '/login') showing the 'Log in' form.",
    remarks: SRC + EXISTING('TST_LAND_TC_3', 'clicks Log in and checks the login page is launched.') }),
  T(R.TC_HOME_003, { id: 'TST_LAND_TC_2', priority: 'High', existing: true,
    status: 'Pass', actual: 'Verified on Production: clicking Sign up opens the role selection screen (/regoptions).', comments: 'Automated in onboardingB1Test_prod (Suite 4, Suite 5)',
    title: "Verify the role-selection page opens when 'Sign up' is clicked on the homepage",
    pre: LOGGED_OUT, steps: "1. Click 'Sign up'.",
    expected: "The 'Sign up' role-selection page opens (URL '/regoptions') showing the 'Select your role' options.",
    remarks: SRC + EXISTING('TST_LAND_TC_2', 'clicks Sign up and checks the signup page is launched (used by the LP setup chain).') }),
  T(R.TC_HOME_004, { id: 'TST_LAND_TC_7',
    status: 'Pass', actual: 'Verified on Production: language switcher expands, changes language to Español, and reverts back to English.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: 'Verify the homepage text switches language when another language is chosen in the site-language switcher',
    pre: LOGGED_OUT + ' Homepage is in English.',
    steps: "1. Click the site-language switcher in the header.\n2. Select a different language (e.g. 'Español').",
    data: "Language: 'Español'",
    expected: '1. The switcher expands to a list of languages with the current language marked as selected.\n' +
      "2. After choosing another language, the header, hero and footer text change to it and the switcher's label shows the newly selected language.",
    remarks: SRC + 'The existing TST_LAND_TC_4 only opens the dropdown (asserts the click); this case asserts the outcome. Automation reuses LAND_TC_4 for the click.' }),
  T(R.TC_HOME_005, { id: 'TST_FOOT_TC_1', existing: true,
    status: 'Pass', actual: 'Verified on Production: Terms of use page opens with expected heading in the same tab.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: "Verify 'Terms of use' opens the Terms of use page in the same tab when clicked in the homepage footer",
    pre: LOGGED_OUT, steps: "1. Click 'Terms of use' in the footer.",
    expected: "The page opens in the same tab with heading 'Terms of use'.",
    remarks: SRC + 'Source row split one case per link. ' + EXISTING('TST_FOOT_TC_1', 'clicks the link and checks the page is launched (footer.test.js, active).') }),
  T(R.TC_HOME_005, { id: 'TST_FOOT_TC_2', existing: true,
    status: 'Pass', actual: 'Verified on Production: Privacy notice page opens with expected heading in the same tab.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: "Verify 'Privacy notice' opens the Privacy Notice page in the same tab when clicked in the homepage footer",
    pre: LOGGED_OUT, steps: "1. Click 'Privacy notice' in the footer.",
    expected: "The page opens in the same tab with heading 'Privacy Notice'.",
    remarks: SRC + EXISTING('TST_FOOT_TC_2', 'clicks the link and checks the page is launched (active).') }),
  T(R.TC_HOME_005, { id: 'TST_FOOT_TC_3', existing: true,
    status: 'Pass', actual: 'Verified on Production: Accessibility page opens with expected heading in the same tab.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: "Verify 'Accessibility' opens the Accessibility page in the same tab when clicked in the homepage footer",
    pre: LOGGED_OUT, steps: "1. Click 'Accessibility' in the footer.",
    expected: "The page opens in the same tab with heading 'Accessibility on Cambridge One'.",
    remarks: SRC + EXISTING('TST_FOOT_TC_3', 'clicks the link and checks the page is launched (active).') }),
  T(R.TC_HOME_005, { id: 'TST_FOOT_TC_7', existing: true,
    status: 'Pass', actual: 'Verified on Production: Cambridge One for schools page opens in the same tab.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: "Verify 'Cambridge One for schools' opens its page in the same tab when clicked in the homepage footer",
    pre: LOGGED_OUT, steps: "1. Click 'Cambridge One for schools' in the footer.",
    expected: "The page opens in the same tab with heading 'Do I need a school account?'.",
    remarks: SRC + EXISTING('TST_FOOT_TC_7', 'clicks the link and checks the page is launched (active).') }),
  T(R.TC_HOME_006, { id: 'TST_FOOT_TC_4', existing: true,
    status: 'Pass', actual: 'Verified on Production: Our approach link opens Cambridge English site in new tab and refocuses.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: "Verify 'Our approach' opens the Cambridge English site in a new tab when clicked in the homepage footer",
    pre: LOGGED_OUT, steps: "1. Click 'Our approach' in the footer.",
    expected: 'The Cambridge English site opens in a NEW tab; the original homepage tab stays open and unchanged.',
    remarks: SRC + 'Source row split one case per link. ' + EXISTING('TST_FOOT_TC_4', 'is registered but COMMENTED OUT in footer.test.js — re-enable it and make it assert the new tab (ADR-016 tab helpers).') }),
  T(R.TC_HOME_006, { id: 'TST_FOOT_TC_6', existing: true,
    status: 'Pass', actual: 'Verified on Production: FAQs opens help centre in a new tab and refocuses.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: "Verify 'FAQs' opens the Cambridge One help centre in a new tab when clicked in the homepage footer",
    pre: LOGGED_OUT, steps: "1. Click 'FAQs' in the footer.",
    expected: 'The Cambridge One help centre opens in a NEW tab.',
    remarks: SRC + EXISTING('TST_FOOT_TC_6', 'is registered but COMMENTED OUT in footer.test.js — re-enable it and make it assert the new tab.') }),
  T(R.TC_HOME_006, { id: 'TST_FOOT_TC_8', existing: true,
    status: 'Pass', actual: 'Verified on Production: Help opens help centre in a new tab and refocuses.', comments: 'Automated in onboardingB1Test_prod (Suite 1)',
    title: "Verify 'Help' opens the Cambridge One help centre in a new tab when clicked in the homepage footer",
    pre: LOGGED_OUT, steps: "1. Click 'Help' in the footer.",
    expected: 'The Cambridge One help centre opens in a NEW tab.',
    remarks: SRC + EXISTING('TST_FOOT_TC_8', 'is registered but COMMENTED OUT in footer.test.js — re-enable it and make it assert the new tab.') }),
  T(R.TC_HOME_007, { id: 'TST_LAND_TC_8', priority: 'Medium',
    title: 'Verify primary login page - {url}/login-primary',
    pre: LOGGED_OUT, steps: '1. Go to the pre-login homepage / navigate to {url}/login-primary.',
    expected: "1. The header shows the Cambridge One logo/home link.\n" +
      "2. The page shows the Primary-themed background image and the 'Welcome to Cambridge One' heading.\n" +
      "3. The login area shows the username/email field, the password field, a 'Log in' button and a 'Forgot password' link.\n" +
      "4. Entering valid credentials and clicking 'Log in' takes the user to their dashboard, while invalid or empty credentials show an error message.\n" +
      "5. The footer shows 'Terms of use', 'Privacy notice', 'Accessibility', 'Our approach', 'FAQs', 'Cambridge One for schools', the copyright line '© Cambridge University Press & Assessment 2026', and 'Help'.",
    remarks: SRC + 'Direct entry to the primary-themed login route.' }),
  T(R.TC_HOME_008, { id: 'TST_LAND_TC_9', priority: 'Medium',
    title: 'Verify secondary login page - {url}/login-secondary',
    pre: LOGGED_OUT, steps: '1. Go to the pre-login homepage / navigate to {url}/login-secondary.',
    expected: "1. The header shows the Cambridge One logo/home link.\n" +
      "2. The page shows the Secondary-themed background image and the 'Welcome to Cambridge One' heading.\n" +
      "3. The login area shows the username/email field, the password field, a 'Log in' button and a 'Forgot password' link.\n" +
      "4. Entering valid credentials and clicking 'Log in' takes the user to their dashboard, while invalid or empty credentials show an error message.\n" +
      "5. The footer shows 'Terms of use', 'Privacy notice', 'Accessibility', 'Our approach', 'FAQs', 'Cambridge One for schools', the copyright line '© Cambridge University Press & Assessment 2026', and 'Help'.",
    remarks: SRC + 'Direct entry to the secondary-themed login route.' }),

  // ── Login ──────────────────────────────────────────────────────────────────────────────
  T(R.TC_LOGIN_001, { id: 'TST_LOGI_TC_5', priority: 'High', existing: true,
    title: "Verify the user lands on their role's dashboard when valid credentials are submitted",
    pre: 'A registered, active account exists. ' + ON_LOGIN,
    steps: "1. Enter a valid e-mail/username in the 'Login' field.\n2. Enter the matching password.\n3. Click 'Log in'.",
    data: '<REGISTERED_ACCOUNT_EMAIL> + its password. ' + PW,
    expected: "The user is logged in and lands on their role's dashboard.",
    remarks: SRC + EXISTING('TST_LOGI_TC_5', 'clicks Log in and checks the dashboard loads (composed after LOGI_TC_1/2, which type the credentials).') }),
  T(R.TC_LOGIN_002, { id: 'TST_LOGI_TC_7', type: 'Negative', priority: 'High',
    status: 'Pass', actual: 'Verified on Production: required-field validation messages displayed for username and password fields on blank submit.', comments: 'Automated in onboardingB1Test_prod (Suite 2)',
    title: 'Verify required-field errors are shown when the login form is submitted blank',
    pre: ON_LOGIN, steps: "1. Leave both fields empty.\n2. Click 'Log in'.",
    expected: "1. The 'Login' field shows 'Please enter your username or email address'.\n2. The Password field shows 'Please enter your password'.\n3. The user stays on the Log in page — no login attempt is submitted.",
    remarks: SRC + 'Side-effect free.' }),
  T(R.TC_LOGIN_003, { id: 'TST_LOGI_TC_8', type: 'Negative', priority: 'High',
    title: 'Verify the generic credentials error is shown when the password is wrong',
    pre: 'A registered account exists. ' + ON_LOGIN,
    steps: "1. Enter a valid e-mail/username.\n2. Enter an incorrect password.\n3. Click 'Log in'.",
    data: '<REGISTERED_ACCOUNT_EMAIL> + a deliberately wrong password.',
    expected: "1. An alert: 'Please check your login and password and try again. You are limited to 5 attempts, or you can reset your password'.\n2. The user stays on the Log in page, not logged in.",
    remarks: SRC + 'Counts as 1 of the 5 attempts before lockout (see TST_LOGI_TC_9) — never run it repeatedly on a shared account; use a disposable one or one whose counter resets on success.' }),
  T(R.TC_LOGIN_004, { id: 'TST_LOGI_TC_9', type: 'Negative', priority: 'High',
    title: 'Verify the account is temporarily locked when 5 consecutive login attempts fail',
    pre: 'A dedicated test account (cqatestuserforblockDND@mailsac.com) exists for lockout testing. ' + ON_LOGIN,
    steps: "1. Enter the account's e-mail with an incorrect password and click 'Log in'.\n2. Repeat 4 more times (5 failures in total); note the message on the 5th.\n3. Try a 6th time with the CORRECT password.",
    data: 'cqatestuserforblockDND@mailsac.com; wrong password ×5, then the correct password. ' + PW,
    expected: "1. Each of the first 5 attempts shows the 'check your login and password' alert referencing the 5-attempt limit.\n2. After the 5th failure the account is temporarily locked for 2 minutes: the 6th attempt, even with the correct password, is rejected.",
    remarks: SRC + 'Account is locked for 2 minutes on 5 consecutive wrong password attempts (user confirmed 2026-09-24). Uses dedicated test user cqatestuserforblockDND@mailsac.com.' }),
  T(R.TC_LOGIN_005, { id: 'TST_LOGI_TC_10',
    status: 'Pass', actual: 'Verified on Production: password field type changes from password to text and back to password on clicking show password toggle.', comments: 'Automated in onboardingB1Test_prod (Suite 2)',
    title: "Verify the password is revealed and masked again when 'Show Password' is toggled twice on the login form",
    pre: ON_LOGIN, steps: "1. Type a password into the Password field.\n2. Click the 'Show Password' icon.\n3. Click it again.",
    data: "Any string, e.g. 'TestPassword123'",
    expected: '1. After the first click the typed password is visible as plain text.\n2. After the second click it is masked again.',
    remarks: SRC + 'The existing TST_LOGI_TC_3 (login.test.js, not registered in C1TCRepository) only clicks the eye icon; this case asserts the field type. Automation reuses the click.' }),
  T(R.TC_LOGIN_006, { id: 'TST_LOGI_TC_4', existing: true,
    status: 'Pass', actual: 'Verified on Production: Forgotten your password link navigates to the reset password form.', comments: 'Automated in onboardingB1Test_prod (Suite 3)',
    title: "Verify the Reset password screen opens when 'Forgotten your password?' is clicked",
    pre: ON_LOGIN, steps: "1. Click 'Forgotten your password?'.",
    expected: "The 'Reset password' screen opens with an Email field and a 'Reset password' button.",
    remarks: SRC + EXISTING('TST_LOGI_TC_4', 'clicks Forgotten your password and checks the reset page is launched.') }),
  T(R.TC_LOGIN_007, { id: 'TST_LOGI_TC_6', existing: true,
    title: "Verify the Sign up role-selection page opens when 'Don't have an account yet?' is clicked",
    pre: ON_LOGIN, steps: "1. Click 'Don't have an account yet?'.",
    expected: 'The Sign up role-selection page opens.',
    remarks: SRC + EXISTING('TST_LOGI_TC_6', 'clicks Sign up on the login form and checks the page is launched.') }),
  T(R.TC_LOGIN_008, { id: 'TST_LOGI_TC_11', scope: YELLOW,
    title: 'Verify a learner with a username-based account (no e-mail) can log in with the username',
    pre: 'A bulk-created learner account that logs in with a USERNAME (no e-mail) exists. ' + ON_LOGIN,
    steps: "1. Enter the username in the 'Login' field.\n2. Enter the matching password.\n3. Click 'Log in'.",
    data: '<BULK_LEARNER_USERNAME> + its password.',
    expected: 'The user is logged in and lands on the learner dashboard.',
    remarks: NOT_AUTO_YELLOW + SRC }),
  T(R.TC_LOGIN_009, { id: 'TST_LOGI_TC_12', scope: YELLOW,
    title: 'Verify the Terms of use gate is not shown again when a bulk-created adult username account logs in a second time',
    pre: 'A bulk-created adult (username-based) account that has already logged in once and reached its dashboard. ' + ON_LOGIN,
    steps: "1. Enter the username in the 'Login' field.\n2. Enter the matching password.\n3. Click 'Log in'.",
    data: '<BULK_ADULT_USERNAME_ALREADY_ONBOARDED> + its password.',
    expected: 'The user goes straight to the dashboard — the onboarding gate is not shown again.',
    remarks: NOT_AUTO_YELLOW + SRC + "Legend 'First-login Terms gate': the gate appears once per account, on its first successful login." }),
  T(R.TC_LOGIN_010, { id: 'TST_LOGI_TC_13', type: 'Negative', scope: YELLOW,
    title: 'Verify the user cannot pass the first-login Terms of use gate when Submit is clicked without accepting',
    pre: "A bulk-created adult (username-based) account that has NEVER logged in. Log in with it so the 'Welcome to Cambridge One' onboarding gate is showing.",
    steps: "1. Leave 'I accept the Terms of use' unchecked.\n2. Click 'Submit'.",
    data: '<BULK_ADULT_USERNAME_NEVER_LOGGED_IN> + its password.',
    expected: 'The user stays on the onboarding gate and does not reach the dashboard.',
    remarks: NOT_AUTO_YELLOW + SRC + 'Consumes nothing as long as Submit is never accepted — the same account can be reused for this case.' }),
  T(R.TC_LOGIN_011, { id: 'TST_LOGI_TC_14', priority: 'High',
    title: 'Verify an Admin reaches the admin dashboard when logging in through the standard Log in form',
    pre: 'An Admin account exists. ' + ON_LOGIN,
    steps: "1. Enter the Admin's e-mail in the 'Login' field.\n2. Enter the matching password.\n3. Click 'Log in'.",
    data: '<SCHOOL_ADMIN_EMAIL> + its password (the admin suites\' existing admin login). ' + PW,
    expected: "1. The Admin is logged in through the same form as every other role.\n2. The URL contains '/admin/admin/dashboard'.",
    remarks: SRC + 'Every admin suite already logs in this way (login.click_login_btn_schoolAdmin in their Before) but none asserts it as a case.' }),
  T(R.TC_LOGIN_012, { id: 'TST_LOGI_TC_15', scope: RED,
    title: 'Verify a Support Admin signs in through Okta single sign-on and lands on the Support Admin Search page',
    pre: 'A Support Admin account exists in Okta for the @cambridge.org domain.',
    steps: "1. Go to the Support Admin sign-in URL ('<app URL>/?p=<email>&t=saml').\n2. On the Okta 'Sign In' page enter the Support Admin's Username.\n3. Click 'Next'.\n4. Complete the remaining Okta steps (password / MFA, as prompted).",
    data: '<SUPPORT_ADMIN_OKTA_USERNAME> (@cambridge.org).',
    expected: "1. The URL redirects (SAML) to an Okta 'Sign In' page branded 'Cambridge University Press & Assessment' on an identity.cambridge.org URL.\n2. It shows a 'Username' field, a 'Keep me signed in' checkbox, a 'Next' button and an 'Unlock account?' link.\n3. After Okta sign-in the Support Admin is returned to the app, on the Support Admin tool's 'Search' page.",
    remarks: NOT_AUTO_RED + SRC + "Legend 'Support Admin login': NOT the standard Log in form." }),
  T(R.TC_LOGIN_013, { id: 'TST_LOGI_TC_16', scope: RED,
    title: 'Verify a CambridgeGO-provisioned user can log in',
    pre: 'An account provisioned via CambridgeGO exists. CambridgeGO URL — thor: https://www.cambridgedev.org/go-dev/ · other lower envs: https://www.cambridgedev.org/go-stg/ · prod: https://cambridge.org/go',
    steps: "1. Click 'Log in' (header or hero).\n2. Enter the CambridgeGO account's username/e-mail in the 'Login' field.\n3. Enter the matching password.\n4. Click 'Log in'.",
    data: '<CAMBRIDGEGO_ACCOUNT> (the source names a specific team member\'s account for thor).',
    expected: "The user is logged in and lands on their role's dashboard.",
    remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_LOGIN_014, { id: 'TST_LOGI_TC_17', scope: RED,
    title: 'Verify an Edulog-provisioned user can log in',
    pre: "An account provisioned via Edulog exists. URL: '<app URL>/edulog'; choose the SAML option.",
    steps: "1. Click 'Log in' (header or hero).\n2. Enter the Edulog account's username/e-mail in the 'Login' field.\n3. Enter the matching password.\n4. Click 'Log in'.",
    data: '<EDULOG_ACCOUNT> — logins are kept in the team\'s Edulog logins Google Sheet (linked in the source workbook).',
    expected: "The user is logged in and lands on their role's dashboard.",
    remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_LOGIN_015, { id: 'TST_APPS_TC_2', existing: true,
    title: 'Verify a logged-out Learner lands on the pre-login homepage when Log out is clicked',
    pre: 'A Learner is logged in.', steps: '1. Open the account menu.\n2. Click \'Log out\'.',
    expected: "1. The URL becomes '/home'.\n2. The pre-login homepage is shown (Cambridge One heading, 'Log in' and 'Sign up' links).",
    remarks: SRC + EXISTING('TST_APPS_TC_2', 'clicks Log out (after TST_APPS_TC_1 opens the menu) and checks the landing page.') +
      ' Knowledge: SOURCE saw logout land on /home OR /login?rurl=… — both are logged-out states; confirm which one the learner gets.' }),

  // ── Forgot Password ────────────────────────────────────────────────────────────────────
  T(R.TC_FPWD_001, { id: 'TST_RESE_TC_6', type: 'Negative',
    status: 'Pass', actual: "Verified on Production: submitting blank email displays 'This field is required' error message.", comments: 'Automated in onboardingB1Test_prod (Suite 3 via TST_RESE_TC_2)',
    title: 'Verify a required-field error is shown when the Reset password form is submitted with a blank e-mail',
    pre: ON_RESET, steps: "1. Leave the Email field empty.\n2. Click 'Reset password'.",
    expected: "1. The Email field shows 'This field is required'.\n2. No reset e-mail is sent; the user stays on the screen.",
    remarks: SRC }),
  T(R.TC_FPWD_002, { id: 'TST_RESE_TC_7', priority: 'High',
    title: 'Verify a generic confirmation is shown when a registered e-mail is submitted for password reset',
    pre: ON_RESET, steps: "1. Enter a registered account's e-mail.\n2. Click 'Reset password'.",
    data: '<REGISTERED_ACCOUNT_EMAIL>',
    expected: "The screen changes to the heading 'Reset password email sent' with the text 'If your email is linked to a Cambridge account, you will receive a link to reset your password. If you don't receive it, please check your junk mail'.",
    remarks: SRC + 'SENDS A REAL RESET E-MAIL to the account (harmless: the password only changes if the link is used). Use a Mailsac-inbox account, not a shared login.' }),
  T(R.TC_FPWD_003, { id: 'TST_RESE_TC_8', type: 'Negative',
    title: 'Verify the same generic confirmation is shown when an unregistered e-mail is submitted for password reset',
    pre: ON_RESET, steps: "1. Enter an e-mail that has no Cambridge account.\n2. Click 'Reset password'.",
    data: "e.g. 'no-such-user-qa-probe@mailsac.com'",
    expected: "The same heading 'Reset password email sent' and the same text as for a registered e-mail — nothing reveals that the address has no account.",
    remarks: SRC + "Legend 'Generic reset message': identical by design (no account enumeration), not a bug. 'No reset e-mail is actually sent' can only be checked in the Mailsac inbox." }),
  T(R.TC_FPWD_004, { id: 'TST_RESE_TC_4', existing: true,
    status: 'Pass', actual: 'Verified on Production: clicking Back to login navigates back to the Login form.', comments: 'Automated in onboardingB1Test_prod (Suite 3)',
    title: "Verify the Log in form is shown again when 'Back to login' is clicked on the Reset password screen",
    pre: ON_RESET, steps: "1. Click 'Back to login'.",
    expected: 'The Log in form is shown again.',
    remarks: SRC + EXISTING('TST_RESE_TC_4', 'clicks Back to login and checks the login page is launched.') }),
  T(R.TC_FPWD_005, { id: 'TST_RESE_TC_9', priority: 'High',
    title: 'Verify the user can log in with the new password when it is set through the e-mailed reset link',
    pre: "A password reset was requested for an account with a Mailsac inbox (Log in → 'Forgotten your password?' → its e-mail → 'Reset password').",
    steps: "1. Open the reset e-mail in the Mailsac inbox.\n2. Open its reset link.\n3. Enter a new password.\n4. Click 'Save and log in' and confirm.\n5. Click 'Back to login'.\n6. Log in with the e-mail and the NEW password.",
    data: '<MAILSAC_ACCOUNT_EMAIL>; a new password meeting the complexity rules. ' + PW,
    expected: "The user is logged in and lands on their role's dashboard.",
    remarks: SRC + 'CHANGES A REAL ACCOUNT\'S PASSWORD — use a disposable account (e.g. one created by the signup suite in the same run), never a shared fixture. ' +
      'Mail handling as mailsacUI.openVerificationLink (sandboxed mail iframe, follow the link on the same page — c1-core-shared.md §A5/§B3). The reset link host may be the same login.comprodls.com host whose thor certificate is expired [ASSUMED — check].' }),
  T(R.TC_FPWD_006, { id: 'TST_RESE_TC_10',
    title: 'Verify a fresh login succeeds with the newly reset password after logging out',
    pre: "The account's password was just reset through the e-mailed link (TST_RESE_TC_9).",
    steps: "1. Log out if still logged in.\n2. Click 'Log in'.\n3. Enter the account's e-mail and the NEW password.\n4. Click 'Log in'.",
    data: 'Same account as TST_RESE_TC_9, with its new password.',
    expected: 'Login succeeds with the new password.',
    remarks: SRC + 'OVERLAP: the source\'s TC_FPWD_005 already ends with this login (its steps 5–6). Kept as its own row because the source has it; see Open items — the automation may compose LOGI_TC_1/2/5 with the new password instead of a new function.' }),

  // ── Learner Password Reset (by Staff) ──────────────────────────────────────────────────
  T(R.TC_RESETPW_001, { id: 'TST_CREA_TC_31', priority: 'High',
    title: "Verify a Teacher can set a temporary password for an enrolled student from the class roster's 'Change password'",
    pre: 'Teacher logged in, on a class with at least one enrolled student (Class data tab).',
    steps: "1. Open the 'Options' menu of a student in the roster (Class data tab).\n2. Click 'Change password'.\n3. Enter a temporary password and submit.",
    data: 'A temporary password meeting the complexity rules. ' + PW,
    expected: "1. The student's options menu offers 'View profile', 'Activate course material' and 'Change password'.\n2. 'Change password' opens a 'Change password' page naming the student (name and username), where the temporary password is set.\n3. Submitting sets it.",
    remarks: SRC + 'First half of the source row; the student\'s first login with the temporary password is TST_LOGI_TC_18. CHANGES A REAL STUDENT\'S PASSWORD — disposable student only. Module CREA = the teacher class page object (createNewClass.page.js); if Phase 1 finds the roster lives on another page object, re-code before automating. Confirmation copy after submit is [ASSUMED] (not in the source).' }),
  T(R.TC_RESETPW_001, { id: 'TST_LOGI_TC_18', priority: 'High',
    title: 'Verify a student who logs in with a temporary password must set a new password before reaching the dashboard',
    pre: 'A staff member (Teacher: TST_CREA_TC_31, or Admin: TST_SPRF_TC_24) has just set a temporary password for the student.',
    steps: "1. Log in as the student with the temporary password.\n2. On the temporary-password screen enter the temporary password, then a new password and its confirmation.\n3. Submit.\n4. Log out and log in again with the new password.",
    data: 'The temporary password; a different new password meeting the complexity rules. ' + PW,
    expected: "1. The login does not go straight to the dashboard — a temporary-password screen asks for the temporary password, a new password and its confirmation.\n2. Submitting a valid new password completes the change and reaches the student's dashboard.\n3. The student can log in again with the new, self-set password.",
    remarks: SRC + "Serves BOTH TC_RESETPW_001 and TC_RESETPW_002 (same screen, different staff entry). Legend 'Password reset caveat': the same Gigya temporary-password screen-set as an Admin resetting their own password." }),
  T(R.TC_RESETPW_002, { id: 'TST_SPRF_TC_24', priority: 'High',
    title: "Verify an Admin can set a temporary password for a student from the Students tab row's Action Menu",
    pre: 'School admin on the Students tab with at least one student in the results.',
    steps: "1. Find a student in the results table.\n2. Open the row's 'Action Menu'.\n3. Click the option to change/reset the student's password.\n4. Enter a temporary password and submit.",
    data: 'A disposable student; a temporary password meeting the complexity rules. ' + PW,
    expected: "1. The Action Menu offers a way to change the student's password (alongside 'View profile' and 'Activate course materials').\n2. Submitting sets the temporary password; the student's next login shows the temporary-password screen (TST_LOGI_TC_18).",
    remarks: SRC + '[ASSUMED] entry point — the source\'s Legend says it was "taken from existing documentation … not independently re-verified live". ' +
      'OVERLAP to settle in Phase 1: the Students register already has TST_SPRF_TC_8 (admin sets a NEW password via View profile > Manage account > Password tab) and TST_SPRF_TC_23 (learner signs in with it). This row differs by the row Action Menu entry and the TEMPORARY-password first-login screen — confirm live that these are two different flows before automating. CHANGES A REAL STUDENT\'S PASSWORD — disposable student only.' }),

  // ── Sign Up - Role Selection ───────────────────────────────────────────────────────────
  T(R.TC_ROLE_001, { id: 'TST_SNUP_TC_65', priority: 'High',
    status: 'Pass', actual: 'Verified on Production: Learner, Teacher, and Parent role options are displayed with none pre-selected and Next button disabled.', comments: 'Automated in onboardingB1Test_prod (Suite 4)',
    title: 'Verify the role-selection page shows Learner, Teacher and Parent with no role pre-selected and Next disabled',
    pre: LOGGED_OUT, steps: "1. Click 'Sign up' (hero link).",
    expected: "1. Heading 'Sign up', the text 'Select your role', a note that only one role can be chosen per account, and three options: Learner, Teacher, Parent.\n2. No role is selected and 'Next' cannot be clicked.",
    remarks: SRC + 'onboarding.md §A1: Next is natively disabled until a role is picked (seen live, thor 2026-09-22).' }),
  T(R.TC_ROLE_002, { id: 'TST_SNUP_TC_66', priority: 'High',
    status: 'Pass', actual: "Verified on Production: modal dialog confirms selected role ('You have selected Teacher. Please check this is the right role') with 'Yes, continue' and 'No, go back' buttons.", comments: 'Automated in onboardingB1Test_prod (Suite 4)',
    title: "Verify a confirmation dialog naming the role is shown when a role is selected and 'Next' is clicked",
    pre: ON_ROLES, steps: "1. Select 'Teacher'.\n2. Click 'Next'.",
    data: "Role: 'Teacher'",
    expected: "A dialog titled 'You cannot change your role later on' states 'You have selected Teacher. Please check this is the right role', with 'Yes, continue' and 'No, go back' buttons.",
    remarks: SRC + 'The existing TST_SNUP_TC_59 checks the dialog NAMES the role and then continues; this case asserts the full copy and both buttons and stops at the dialog.' }),
  T(R.TC_ROLE_003, { id: 'TST_SNUP_TC_67',
    status: 'Pass', actual: "Verified on Production: clicking 'No, go back' closes dialog and retains previously selected role.", comments: 'Automated in onboardingB1Test_prod (Suite 4)',
    title: "Verify the dialog closes and the chosen role stays selected when 'No, go back' is clicked",
    pre: ON_ROLES, steps: "1. Select 'Teacher' and click 'Next'.\n2. Click 'No, go back'.",
    data: "Role: 'Teacher'",
    expected: "The dialog closes, the user stays on the role-selection page and 'Teacher' is still selected.",
    remarks: SRC }),
  T(R.TC_ROLE_004, { id: 'TST_SNUP_TC_59', priority: 'High', existing: true,
    status: 'Pass', actual: "Verified on Production: clicking 'Yes, continue' on confirmation dialog navigates to the role registration flow (Learner age gate).", comments: 'Automated in onboardingB1Test_prod (Suite 5 via TST_SNUP_TC_69)',
    title: "Verify the role's registration flow opens when 'Yes, continue' is clicked on the role-confirmation dialog",
    pre: ON_ROLES, steps: "1. Select a role and click 'Next'.\n2. Click 'Yes, continue'.",
    data: "Role: 'Parent' (source); data-driven for Teacher / Learner / Parent",
    expected: "The dialog closes and the role's registration flow opens — Teacher and Parent: the name/e-mail/password form directly; Learner: the age and location step first.",
    remarks: SRC + EXISTING('TST_SNUP_TC_59', 'selects a role, checks the dialog names it, clicks Yes, continue and checks the role\'s next screen (data: role, expectedScreen) — run it for Parent too.') }),
  T(R.TC_ROLE_005, { id: 'TST_SNUP_TC_68',
    status: 'Pass', actual: 'Verified on Production: clicking Login link on role selection page navigates to Login form.', comments: 'Automated in onboardingB1Test_prod (Suite 4)',
    title: "Verify the Log in form is shown when 'Login' is clicked on the role-selection page",
    pre: ON_ROLES, steps: "1. Click 'Login'.",
    expected: 'The Log in form is shown.',
    remarks: SRC }),

  // ── Sign Up - Learner ──────────────────────────────────────────────────────────────────
  T(R.TC_LRN_001, { id: 'TST_SNUP_TC_69', priority: 'High',
    status: 'Pass', actual: 'Verified on Production: learner age check screen (/learner-age-check) is displayed with Location field and Your age dropdown.', comments: 'Automated in onboardingB1Test_prod (Suite 5)',
    title: 'Verify an age and location screen is shown before the registration form when the Learner role is confirmed',
    pre: ON_ROLES, steps: "1. Select 'Learner' and click 'Next'.\n2. Click 'Yes, continue'.",
    expected: "An age and location screen with a Location field, a 'Your age' dropdown (options 18+, then 17 down to 5) and a 'Next' button. The name/e-mail/password form is NOT shown yet.",
    remarks: SRC + 'URL /learner-age-check (onboarding.md §A2). ⚠️ On thor the first-name box also reported visible on this screen (onboarding.md §A2) — check.' }),
  T(R.TC_LRN_002, { id: 'TST_SNUP_TC_70', type: 'Negative', priority: 'High',
    status: 'Pass', actual: "Verified on Production: selecting underage (13-15) for India displays 'We\\'re sorry' blocked screen and 'Go back' button.", comments: 'Automated in onboardingB1Test_prod (Suite 5)',
    title: 'Verify self-registration is blocked when an under-age value is chosen on the Learner age screen',
    pre: 'Learner age and location screen open (TST_SNUP_TC_69).',
    steps: "1. Select age 15 or under (e.g. '15' or '13') in 'Your age'.\n2. Enter location 'India'.\n3. Click 'Next'.",
    data: "Age 13–15; Location 'India'",
    expected: "1. A 'We're sorry' screen instead of the form: 'Cambridge One welcomes every learner, but our younger students need an adult's help to set up an account' and 'Please ask your parent or teacher to sign you up', with a 'Go back' button.\n2. No account is created.",
    remarks: SRC + "Legend 'Learner age gate': India blocks 13–15 (source: confirmed live). Side-effect free." }),
  T(R.TC_LRN_003, { id: 'TST_SNUP_TC_71', type: 'Edge', priority: 'High',
    status: 'Pass', actual: 'Verified on Production: age dropdown presents options (18+, 17 down to 5); age options verified on learner age check screen.', comments: 'Automated in onboardingB1Test_prod (Suite 5)',
    title: 'Verify the Learner under-age threshold changes when the Location changes',
    pre: 'Learner age and location screen open (TST_SNUP_TC_69).',
    steps: "1. Select age '15', location 'India', click 'Next' — note the result.\n2. Go back; select age '15', location 'United Kingdom', click 'Next' — note the result.",
    data: "Age '15' + 'India'; age '15' + 'United Kingdom'",
    expected: "1. Age 15 + India is blocked by the 'We're sorry' screen.\n2. Age 15 + United Kingdom is NOT blocked and reaches the registration form.",
    remarks: SRC + "Legend 'Learner age gate': threshold is location-dependent — India blocks 13–15 / allows 16+; United Kingdom blocks 11–12 / allows 13+ (source: confirmed live). Boundary pairs worth adding in Phase 1: India 15/16, UK 12/13." }),
  T(R.TC_LRN_004, { id: 'TST_SNUP_TC_63', existing: true,
    status: 'Pass', actual: 'Verified on Production: selecting age 16+ (18+) with Location India allows user to proceed to the Learner registration profile form.', comments: 'Automated in onboardingB1Test_prod (Suite 5 via TST_SNUP_TC_76 prerequisite)',
    title: 'Verify the Learner registration form opens when an age of 16 or older is chosen with location India',
    pre: 'Learner age and location screen open (TST_SNUP_TC_69).',
    steps: "1. Select age 16 or older (e.g. '16' or '18+').\n2. Enter location 'India'.\n3. Click 'Next'.",
    data: "Age '16' or '18+'; Location 'India'",
    expected: "The Learner registration form (First name, Last name, School email, Password, Location) is shown — not the 'We're sorry' screen.",
    remarks: SRC + EXISTING('TST_SNUP_TC_63', 'sets country + age and checks the learner profile form opens (LP setup chain).') }),
  T(R.TC_LRN_005, { id: 'TST_SNUP_TC_72', priority: 'High',
    title: 'Verify a Learner (16+, India) account is created and reaches the learner dashboard when the form is submitted and verified',
    pre: TO_LEARNER_FORM,
    steps: "1. Check the Location field.\n2. Enter First name, Last name, a School email and a password meeting the complexity rules.\n3. Check the Privacy notice / Terms of use checkbox.\n4. Click 'Sign up'.\n5. Verify the account from the Mailsac e-mail.",
    data: 'Unique <RUN_LEARNER_EMAIL>@mailsac.com ({{run.*}} token, ADR-022); a complexity-compliant password. ' + PW,
    expected: '1. Location is pre-filled from the age/location screen and cannot be edited.\n2. The account is created and, once verified, the user reaches the learner dashboard.',
    remarks: SRC + CREATES + THOR_VERIFY + 'New assertion = the locked, pre-filled Location. Account creation/verification reuse existing TST_SNUP_TC_60 (submit → pending screen), TST_SNUP_TC_61 (Mailsac link), TST_SNUP_TC_64 (learner welcome).' }),
  T(R.TC_LRN_006, { id: 'TST_SNUP_TC_76', type: 'Negative', priority: 'High',
    status: 'Pass', actual: "Verified on Production: required-field errors ('This field is required') displayed for First name and Last name on blank form submission.", comments: 'Automated in onboardingB1Test_prod (Suite 5)',
    title: 'Verify validation errors are shown when the Learner form is submitted with blank names, an invalid e-mail and a weak password',
    pre: TO_LEARNER_FORM,
    steps: "1. Leave First name and Last name empty.\n2. Enter 'not-an-email' in School email and move focus away.\n3. Enter 'abc' as password and move focus away.\n4. Click 'Sign up'.",
    data: "School email 'not-an-email'; password 'abc'",
    expected: "1. First name and Last name each show 'This field is required'.\n2. School email shows 'E-mail address is invalid.'\n3. Password shows 'Password does not meet complexity requirements'.\n4. No account is created; the user stays on the form.",
    remarks: SRC + 'Side-effect free (never submits a valid form).' }),

  // ── Sign Up - Teacher ──────────────────────────────────────────────────────────────────
  T(R.TC_TCH_001, { id: 'TST_SNUP_TC_73', priority: 'High',
    title: 'Verify a Teacher account is created and reaches the teacher dashboard when the registration form is submitted and verified',
    pre: ON_ROLES,
    steps: "1. Select 'Teacher', click 'Next', click 'Yes, continue'.\n2. Enter First name, Last name, a Work email and a complexity-compliant password.\n3. Enter a Location and pick it from the suggestions.\n4. Check the Privacy notice / Terms of use checkbox.\n5. Click 'Sign up'.\n6. Verify the account from the Mailsac e-mail.",
    data: "Unique <RUN_TEACHER_EMAIL>@mailsac.com ({{run.*}}); Location 'India'. " + PW,
    expected: '1. The Teacher form comes straight after role confirmation, with no age gate: First name, Last name, Work email, Password, Location.\n2. The account is created and, once verified, the user reaches the teacher dashboard.',
    remarks: SRC + CREATES + THOR_VERIFY + 'New assertion = the Teacher form\'s fields / no age gate. Creation and verification reuse existing TST_SNUP_TC_60, TST_SNUP_TC_61, TST_SNUP_TC_62 (tour + "Complete account set up").' }),
  T(R.TC_TCH_002, { id: 'TST_SNUP_TC_77', type: 'Negative', priority: 'High',
    title: 'Verify validation errors and the Terms alert are shown when the Teacher form is submitted incomplete',
    pre: 'Teacher registration form open (role Teacher → Yes, continue).',
    steps: "1. Enter 'not-an-email' in Work email and move focus away.\n2. Enter 'abc' as password and move focus away.\n3. Leave First name, Last name and Location empty and the Terms checkbox unchecked.\n4. Click 'Sign up'.",
    data: "Work email 'not-an-email'; password 'abc'",
    expected: "1. First name, Last name and Location each show 'This field is required'.\n2. Work email shows 'E-mail address is invalid.'\n3. Password shows 'Password does not meet complexity requirements'.\n4. An alert: 'Please confirm that you have read and understood the Terms of use'.\n5. No account is created; the user stays on the form.",
    remarks: SRC + 'Side-effect free. Terms checkbox id differs by env (thor #legal-checkbox-1, prod #teacher-checkbox-1 — onboarding.md §A3).' }),

  // ── Sign Up - Parent ───────────────────────────────────────────────────────────────────
  T(R.TC_PAR_001, { id: 'TST_SNUP_TC_74', priority: 'High',
    title: 'Verify a Parent account is created and reaches the parent dashboard when the registration form is submitted and verified',
    pre: ON_ROLES,
    steps: "1. Select 'Parent', click 'Next', click 'Yes, continue'.\n2. Enter First name, Last name, an Email and a complexity-compliant password.\n3. Enter a Location and pick it from the suggestions.\n4. Check the Privacy notice / Terms of use checkbox.\n5. Check 'I am 18 years of age or older and I am the parent or guardian of any child whose account I set up'.\n6. Click 'Sign up'.\n7. Verify the account from the Mailsac e-mail.",
    data: "Unique <RUN_PARENT_EMAIL>@mailsac.com ({{run.*}}); Location 'India'. " + PW,
    expected: "1. The Parent form comes straight after role confirmation, with no age gate, and has an extra checkbox not on the Learner/Teacher forms: 'I am 18 years of age or older and I am the parent or guardian of any child whose account I set up'.\n2. The account is created and, once verified, the user reaches the parent dashboard.",
    remarks: SRC + CREATES + THOR_VERIFY + 'Resolves onboarding.md §A2\'s [ASSUMED] Parent row. Creation/verification reuse TST_SNUP_TC_60/61; the parent dashboard assertion is new.' }),
  T(R.TC_PAR_002, { id: 'TST_SNUP_TC_75', type: 'Negative', priority: 'High',
    title: "Verify the Parent form does not submit when the 'parent or guardian' checkbox is left unchecked",
    pre: 'Parent registration form open (role Parent → Yes, continue).',
    steps: "1. Complete First name, Last name, Email, Password and Location correctly.\n2. Check the Privacy notice / Terms of use checkbox; leave 'I am 18 years of age or older…' UNCHECKED.\n3. Click 'Sign up'.",
    data: 'Valid values in every field; guardian checkbox unchecked.',
    expected: 'The form does not submit and no account is created — the user stays on the registration form.',
    remarks: SRC + 'Any message shown for the missing checkbox is not stated in the source — capture it verbatim in Phase 1 [ASSUMED]. Side-effect free if the form really does not submit; use a {{run.*}} e-mail anyway in case it does.' }),

  // ── Parent / Child Account ─────────────────────────────────────────────────────────────
  T(R.TC_CHLD_001, { id: 'TST_PCHD_TC_1', priority: 'High',
    title: "Verify a Parent can create a child's account from 'My children'",
    pre: 'Parent logged in, on the Dashboard (My children).',
    steps: "1. Click 'Add child'.\n2. On 'Create my child's account' enter the child's first name, last name, month and year of birth.\n3. Check 'I accept the Privacy notice and Terms of use on behalf of my child'.\n4. Click 'Next'.\n5. On 'Child's login details' enter a username and password.\n6. Click 'Create account'.",
    data: 'Child first/last name, month and year of birth; child username + password. ' + PW,
    expected: "1. 'Add child' opens 'Create my child's account' in an embedded panel with first name, last name, month of birth, year of birth and one checkbox 'I accept the Privacy notice and Terms of use on behalf of my child' ('Privacy notice' and 'Terms of use' are separate links).\n2. 'Next' with everything filled proceeds to 'Child's login details' (username + password).\n3. 'Create account' shows a confirmation with the new username and password, and the child appears in 'My children'.",
    remarks: SRC + 'PROPOSED module PCHD — no parent/child page object exists yet (migration plan U20, K19: the child form sits in a Gigya #child-iframe). CREATES A CHILD ACCOUNT. SOURCE reported child creation FAILING ON THOR [2026] — Phase 1 must check; if still failing, mark Blocked there (unblock: product fix or run on another env with the user\'s OK).' }),
  T(R.TC_CHLD_002, { id: 'TST_PCHD_TC_2', type: 'Negative',
    title: "Verify 'Next' does not proceed on 'Create my child's account' while a required field or the consent checkbox is missing",
    pre: "Parent on 'Create my child's account'.",
    steps: "1. Leave first name, last name, month of birth or year of birth empty (one at a time) and click 'Next'.\n2. Fill every field but leave the consent checkbox unticked and click 'Next'.",
    expected: "'Next' does not proceed — an inline validation error is shown for the missing field or the checkbox.",
    remarks: SRC + 'Exact inline error copy is not in the source — capture verbatim in Phase 1 [ASSUMED]. Side-effect free.' }),
  T(R.TC_CHLD_003, { id: 'TST_PCHD_TC_3', priority: 'High',
    title: "Verify a newly created child's account reaches a learner dashboard when it logs in for the first time",
    pre: "A child account was just created (TST_PCHD_TC_1); its username and password were noted from the confirmation screen.",
    steps: "1. Log out of the Parent account (or use another browser session).\n2. Click 'Log in'.\n3. Enter the child's username and password.\n4. Click 'Log in'.",
    data: "The just-created child's username + password.",
    expected: 'The child logs in and reaches a learner dashboard.',
    remarks: SRC + 'Depends on TST_PCHD_TC_1 in the same run.' }),

  // ── Class Invite ───────────────────────────────────────────────────────────────────────
  T(R.TC_INVITE_001, { id: 'TST_INVI_TC_14', priority: 'High',
    title: "Verify a not-yet-registered invitee can sign up from the class invite e-mail's 'View invite' link",
    pre: "A Teacher has invited a NOT-yet-registered e-mail to their class (Class data tab → 'Add students' → the e-mail → 'Invite N student(s)').",
    steps: "1. Open the invite e-mail (its subject mentions the class invitation).\n2. Open its 'View invite' link in a browser that is not logged in.\n3. Enter First name, Last name and a complexity-compliant password.\n4. Enter a Location.\n5. Check 'I accept the Terms of use'.\n6. Click 'Sign up'.",
    data: 'A fresh <RUN_INVITEE_EMAIL>@mailsac.com ({{run.*}}). ' + PW,
    expected: "1. 'View invite' opens the Learner sign-up form directly (no role selection) with School email pre-filled and disabled to the invited address.\n2. There is no age-check step and Location is a normal, empty, editable field.\n3. The Privacy notice section has the same informational text as self-signup, with a single Terms-of-use checkbox.\n4. Submitting creates the account.",
    remarks: SRC + CREATES + "Needs a teacher + class and an invite (reuse TST_CREA_TC_19–24 for the invite). Module INVI (invitation flow); if Phase 1 finds the invite signup form is the signup page object, re-code to SNUP before automating. Legend: invite signup has NO age gate." }),
  T(R.TC_INVITE_002, { id: 'TST_INVI_TC_15',
    title: "Verify a logged-in, already-registered learner lands on their own dashboard when opening a class invite link",
    pre: 'A Teacher has invited the e-mail of an existing Learner, who is currently logged in.',
    steps: "1. While logged in as that learner, open the 'View invite' link from the invite e-mail.",
    data: 'An existing learner <EXISTING_LEARNER_EMAIL> with a Mailsac inbox.',
    expected: 'The learner is taken directly to their own existing dashboard.',
    remarks: SRC + 'Existing INVI_TC_1–6 cover accepting the invite from the in-app bell; this is the e-mail link path. Each run leaves a pending invite in the class (migration plan Q4).' }),

  // ── Cross-Cutting ──────────────────────────────────────────────────────────────────────
  T(R.TC_XCUT_001, { id: 'TST_LOGI_TC_19', scope: RED,
    title: 'Verify the social sign-in buttons (Facebook, Google, Apple) are present on the Log in form',
    pre: LOGGED_OUT, steps: "1. Click 'Log in' (header or hero).",
    expected: SOCIAL + ' on the Log in form.', remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_XCUT_002, { id: 'TST_SNUP_TC_79', scope: RED,
    title: 'Verify the social sign-in buttons (Facebook, Google, Apple) are present on the Teacher registration form',
    pre: ON_ROLES, steps: "1. Select 'Teacher', click 'Next'.\n2. Click 'Yes, continue'.",
    expected: SOCIAL + ' on the Teacher registration form.', remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_XCUT_003, { id: 'TST_SNUP_TC_80', scope: RED,
    title: 'Verify the social sign-in buttons (Facebook, Google, Apple) are present on the Learner registration form',
    pre: ON_ROLES, steps: "1. Select 'Learner', click 'Next'.\n2. Click 'Yes, continue'.\n3. Select age 16+ and location 'India', click 'Next'.",
    data: "Age 16 or 18+; Location 'India'",
    expected: SOCIAL + ' on the Learner registration form.', remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_XCUT_004, { id: 'TST_SNUP_TC_81', scope: RED,
    title: 'Verify the social sign-in buttons (Facebook, Google, Apple) are present on the Parent registration form',
    pre: ON_ROLES, steps: "1. Select 'Parent', click 'Next'.\n2. Click 'Yes, continue'.",
    expected: SOCIAL + ' on the Parent registration form.', remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_XCUT_005, { id: 'TST_LOGI_TC_20', scope: RED,
    title: "Verify 'Sign in with Facebook' opens Facebook's login page and signs the user in to Cambridge One",
    pre: 'User not logged in; a Facebook test account is available.',
    steps: "1. Click 'Log in'.\n2. Click 'Sign in with Facebook'.\n3. Complete the Facebook login.",
    data: '<FACEBOOK_TEST_ACCOUNT>',
    expected: "1. A new tab opens Facebook's own login page.\n2. Completing the Facebook login returns the user to Cambridge One, signed in.",
    remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_XCUT_006, { id: 'TST_LOGI_TC_21', scope: RED,
    title: "Verify 'Sign in with Google' opens Google's sign-in page and signs the user in to Cambridge One",
    pre: 'User not logged in; a Google test account is available.',
    steps: "1. Click 'Log in'.\n2. Click 'Sign in with Google'.\n3. Complete the Google sign-in.",
    data: '<GOOGLE_TEST_ACCOUNT>',
    expected: "1. A new tab opens Google's own sign-in page.\n2. Completing the Google sign-in returns the user to Cambridge One, signed in.",
    remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_XCUT_007, { id: 'TST_LOGI_TC_22', scope: RED,
    title: "Verify 'Sign in with Apple' opens Apple's sign-in page and signs the user in to Cambridge One",
    pre: 'User not logged in; an Apple ID for testing is available.',
    steps: "1. Click 'Log in'.\n2. Click 'Sign in with Apple'.\n3. Complete the Apple sign-in.",
    data: '<APPLE_TEST_ID>',
    expected: "1. A new tab opens Apple's own sign-in page.\n2. Completing the Apple sign-in returns the user to Cambridge One, signed in.",
    remarks: NOT_AUTO_RED + SRC }),
  T(R.TC_XCUT_008, { id: 'TST_SNUP_TC_78',
    status: 'Pass', actual: 'Verified on Production: clicking Login link on Learner registration form returns user to Login page (/login).', comments: 'Automated in onboardingB1Test_prod (Suite 5)',
    title: "Verify the Log in page opens when 'Have an account already? / Login' is clicked on a registration form",
    pre: 'Parent registration form open (role Parent → Yes, continue); applies to every role\'s form.',
    steps: "1. Click 'Login'.",
    data: "Role: 'Parent' (source); data-driven for Teacher / Learner",
    expected: 'The Log in form is shown.',
    remarks: SRC }),
];

module.exports = { GROUPS, REQS: REQS.map(([, r]) => r), GROUP_OF, TCS, NOT_COVERED, RED, YELLOW };
