"use strict";
/**
 * Generates Claude Code skill pointers from the repo's canonical skills.
 *
 * The skills live in `.agent/skills/<name>/SKILL.md` (repo root) — the single source, also read by
 * the team's other AI tools. Claude Code only auto-discovers skills under `.claude/skills/`, so this
 * script writes one small pointer per skill there: the source's frontmatter copied verbatim (its
 * `name` + `description` are what Claude uses to pick the skill on its own) and a body that sends
 * Claude to the source file. Pointers are generated, never hand-edited.
 *
 * Usage (from the repo root or from testAutomation_v1.0 — paths resolve from this file):
 *   node testAutomation_v1.0/tooling/syncClaudeSkills.js           write / refresh every pointer
 *   node testAutomation_v1.0/tooling/syncClaudeSkills.js --check   report drift only; exit 1 if any
 *
 * Run it after adding a skill, or after changing a skill's name or description.
 */
const fs = require("fs");
const path = require("path");

// tooling/ -> testAutomation_v1.0/ -> repo root; independent of the caller's cwd.
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const SRC_DIR = path.join(REPO_ROOT, ".agent", "skills");
const DST_DIR = path.join(REPO_ROOT, ".claude", "skills");
// Marks a pointer as ours, so stale-pointer cleanup never touches a hand-made Claude skill.
const MARKER = "GENERATED by testAutomation_v1.0/tooling/syncClaudeSkills.js";
const CHECK = process.argv.includes("--check");

// Agent Skills standard limits; a skill outside them risks being cut off or not discovered at all.
const MAX_DESCRIPTION = 1024;
const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/** Flattens the `description:` value — inline, or a `>` / `|` block of indented lines. */
function descriptionText(frontmatter) {
  const lines = frontmatter.split("\n");
  const i = lines.findIndex((l) => /^description:/.test(l));
  const inline = lines[i].replace(/^description:\s*/, "");
  if (!/^[>|][+-]?$/.test(inline)) return inline.replace(/^["']|["']$/g, "").trim();
  const block = [];
  for (let j = i + 1; j < lines.length && /^\s+\S|^\s*$/.test(lines[j]); j++) block.push(lines[j].trim());
  return block.join(" ").replace(/\s+/g, " ").trim();
}

/**
 * Returns the frontmatter block (without the --- fences) or throws — a skill without a valid one
 * cannot be discovered, so failing loudly beats writing a pointer Claude would ignore.
 */
function readFrontmatter(file, dirName) {
  const rel = path.relative(REPO_ROOT, file);
  const text = fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n");
  const match = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!match) throw new Error(`${rel} has no YAML frontmatter`);
  const name = (match[1].match(/^name:\s*(\S+)/m) || [])[1];
  if (!name || !/^description:/m.test(match[1])) throw new Error(`${rel} frontmatter lacks name or description`);
  if (name !== dirName || !NAME_RE.test(name) || name.length > 64) {
    throw new Error(`${rel}: name "${name}" must equal its folder name and be lower-case-hyphenated, max 64 chars`);
  }
  const len = descriptionText(match[1]).length;
  if (len > MAX_DESCRIPTION) throw new Error(`${rel}: description is ${len} chars; the limit is ${MAX_DESCRIPTION}`);
  return match[1];
}

function pointerFor(name, frontmatter) {
  const src = `.agent/skills/${name}/SKILL.md`;
  return [
    "---",
    frontmatter,
    "---",
    "",
    `<!-- ${MARKER} from ${src}.`,
    "     Do not edit: edit the source, then run `node testAutomation_v1.0/tooling/syncClaudeSkills.js`. -->",
    "",
    `# ${name} (pointer)`,
    "",
    `The instructions for this skill live in **\`${src}\`** — the single source, shared with the`,
    "team's other AI tools. **Read that file now and follow it exactly.** Every file it refers to",
    `(phase files, reference files) is under \`.agent/skills/${name}/\`.`,
    "",
  ].join("\n");
}

function main() {
  const skills = fs
    .readdirSync(SRC_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && fs.existsSync(path.join(SRC_DIR, d.name, "SKILL.md")))
    .map((d) => d.name)
    .sort();

  const problems = [];
  for (const name of skills) {
    const expected = pointerFor(name, readFrontmatter(path.join(SRC_DIR, name, "SKILL.md"), name));
    const target = path.join(DST_DIR, name, "SKILL.md");
    const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
    if (current === expected) continue;
    if (CHECK) {
      problems.push(`${current === null ? "missing" : "out of date"}: .claude/skills/${name}/SKILL.md`);
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, expected);
      console.log(`${current === null ? "created" : "updated"}: .claude/skills/${name}/SKILL.md`);
    }
  }

  // A pointer whose source skill was removed or renamed would keep offering a dead skill to Claude.
  if (fs.existsSync(DST_DIR)) {
    for (const d of fs.readdirSync(DST_DIR, { withFileTypes: true })) {
      const file = path.join(DST_DIR, d.name, "SKILL.md");
      if (!d.isDirectory() || skills.includes(d.name) || !fs.existsSync(file)) continue;
      if (!fs.readFileSync(file, "utf8").includes(MARKER)) continue; // hand-made skill: leave it
      if (CHECK) {
        problems.push(`stale (no source skill): .claude/skills/${d.name}/SKILL.md`);
      } else {
        fs.rmSync(path.join(DST_DIR, d.name), { recursive: true, force: true });
        console.log(`removed stale: .claude/skills/${d.name}/`);
      }
    }
  }

  if (CHECK) {
    if (problems.length) {
      problems.forEach((p) => console.log(p));
      console.log("Run: node testAutomation_v1.0/tooling/syncClaudeSkills.js");
      process.exit(1);
    }
    console.log(`OK — ${skills.length} skill pointer(s) in sync.`);
  } else {
    console.log(`Done — ${skills.length} skill pointer(s) checked.`);
  }
}

// An invalid skill is a message for the person editing it, not a stack trace.
try {
  main();
} catch (err) {
  console.error(`ERROR: ${err.message}`);
  process.exit(1);
}
